# Generated by Django 4.0.4 on 2022-12-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50, verbose_name='Name')),
                ('skype_group_id', models.CharField(default='', max_length=200, verbose_name='SkypeGroupId')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
