# Generated by Django 4.0.4 on 2022-12-27 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50, verbose_name='Name')),
                ('ip_address', models.CharField(default='name', max_length=50, verbose_name='IP')),
                ('api_url', models.CharField(default='', max_length=200, verbose_name='API Url')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50, verbose_name='Name')),
                ('skype_id', models.CharField(default='', max_length=200, verbose_name='SkypeGroupId')),
                ('email', models.EmailField(default='sales@example.com', max_length=50, verbose_name='Email')),
                ('is_admin', models.BooleanField(default=False, verbose_name='IsAdmin')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Description')),
                ('switch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voip.switch', verbose_name='Switch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voip.sales', verbose_name='Sales'),
        ),
    ]
