# Generated by Django 4.0.4 on 2022-12-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0002_switch_sales_customer_sales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Staff',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='sales',
            new_name='staff',
        ),
    ]
