# Generated by Django 4.0.4 on 2022-12-27 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0004_alter_staff_skype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='voip.staff', verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_customers', to='voip.staff', verbose_name='Sales'),
        ),
    ]
