# Generated by Django 4.0.4 on 2022-12-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0005_customer_creator_alter_customer_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='switch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voip.switch', verbose_name='Switch'),
        ),
    ]
