# Generated by Django 4.0.4 on 2022-12-27 06:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0006_customer_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Amount')),
                ('invoice_id', models.CharField(blank=True, default='', max_length=50, verbose_name='InvoiceId')),
                ('invoice_url', models.CharField(blank=True, default='', max_length=50, verbose_name='InvoiceUrl')),
                ('is_gateway_confirmed', models.BooleanField(default=False, verbose_name='GatewayConfirm')),
                ('gateway_confirmed_time', models.DateTimeField(default=None, null=True)),
                ('is_expired', models.BooleanField(default=False, verbose_name='IsExpired')),
                ('expired_time', models.DateTimeField(default=None, null=True)),
                ('is_switch_credited', models.BooleanField(default=False, verbose_name='SwitchCredit')),
                ('switch_credited_time', models.DateTimeField(default=None, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mark', models.CharField(blank=True, default='', max_length=1000, verbose_name='Mark')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voip.customer', verbose_name='Switch')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
