# Generated by Django 4.0.4 on 2022-12-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0007_recharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='invoice_create_error',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Invoice Create Error'),
        ),
    ]
