# Generated by Django 4.0.4 on 2022-12-29 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0008_recharge_invoice_create_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='CustomerName'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voip.customer', verbose_name='Customer'),
        ),
    ]
