# Generated by Django 4.0.4 on 2022-12-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0009_recharge_customer_name_alter_recharge_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='expired_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='gateway_confirmed_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='switch_credited_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
