# Generated by Django 4.0.4 on 2022-12-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0011_recharge_credit_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='is_switch_credit_success',
            field=models.BooleanField(default=False, verbose_name='SwitchCredit'),
        ),
    ]
