# Generated by Django 4.0.4 on 2022-12-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0012_recharge_is_switch_credit_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='pay_address',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='InvoiceId'),
        ),
        migrations.AddField(
            model_name='recharge',
            name='pay_network',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Network'),
        ),
    ]
