# Generated by Django 4.0.4 on 2022-12-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0014_recharge_pay_currency_alter_recharge_pay_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='is_switch_credit_success',
            field=models.BooleanField(default=False, verbose_name='CreditSuccess'),
        ),
    ]
