# Generated by Django 4.0.4 on 2022-12-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0015_alter_recharge_is_switch_credit_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='is_expired_notified',
            field=models.BooleanField(default=False, verbose_name='ExpiredNotified'),
        ),
    ]
