# Generated by Django 4.0.4 on 2023-01-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0016_recharge_is_expired_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=50, verbose_name='Number')),
                ('call_model', models.CharField(choices=[('Direct', 'Direct'), ('Bypass', 'Bypass'), ('Auto', 'Auto'), ('Block', 'Block')], default='Auto', max_length=10)),
                ('country', models.CharField(choices=[('86', '86'), ('852', '852')], default='86', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Description')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
