# Generated by Django 4.0.4 on 2023-01-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0017_featurenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cfg_asr',
            field=models.FloatField(default=0.18, verbose_name='ASR'),
        ),
    ]
