# Generated by Django 4.0.4 on 2023-01-12 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0018_customer_cfg_asr'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='127.0.0.1', max_length=50, verbose_name='IP')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Description')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voip.customer', verbose_name='inbound_gateways')),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
    ]
