# Generated by Django 4.0.4 on 2023-01-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0019_inboundgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cfg_enable_sky_net',
            field=models.BooleanField(default=False, verbose_name='SkyNet'),
        ),
    ]
