# Generated by Django 4.0.4 on 2023-01-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0020_customer_cfg_enable_sky_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='skype_group_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SkypeGroupId'),
        ),
    ]
