# Generated by Django 4.0.4 on 2023-01-12 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0021_alter_customer_skype_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundgateway',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voip.customer'),
        ),
    ]
