# Generated by Django 4.0.4 on 2023-01-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0022_alter_inboundgateway_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurenumber',
            name='call_model',
            field=models.CharField(choices=[('Direct', 'Direct'), ('Auto', 'Auto'), ('Block', 'Block')], default='Auto', max_length=10),
        ),
    ]
