# Generated by Django 4.0.4 on 2023-01-13 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0023_alter_featurenumber_call_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurenumber',
            options={'ordering': ['created_time']},
        ),
        migrations.AddField(
            model_name='featurenumber',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
