# Generated by Django 4.0.4 on 2023-01-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0024_alter_featurenumber_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurenumber',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='customer',
            name='cfg_ringtone',
            field=models.BooleanField(default=False, verbose_name='RingTone'),
        ),
    ]
