# Generated by Django 4.0.4 on 2023-01-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0025_alter_featurenumber_options_customer_cfg_ringtone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Prefix'),
        ),
    ]
