# Generated by Django 4.0.4 on 2023-01-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0026_customer_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['prefix']},
        ),
    ]
