# Generated by Django 4.0.4 on 2023-01-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0027_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cfg_mix_ratio',
            field=models.FloatField(default=0.1, verbose_name='MixRatio'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(default='https://example.com', max_length=100, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='skype_group_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='SkypeGroupId'),
        ),
    ]
