# Generated by Django 4.0.4 on 2023-01-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0028_customer_cfg_mix_ratio_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cfg_mix_ratio',
            field=models.FloatField(default=0, verbose_name='MixRatio'),
        ),
    ]
