# Generated by Django 4.0.4 on 2023-01-30 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0029_alter_customer_cfg_mix_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='86', max_length=10)),
                ('number', models.CharField(default='', max_length=20, verbose_name='Number')),
                ('file', models.CharField(blank=True, default='', max_length=50)),
                ('gateway', models.CharField(blank=True, default='', max_length=50)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
