# Generated by Django 4.0.4 on 2023-01-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0030_calllog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='country',
        ),
        migrations.AddField(
            model_name='calllog',
            name='prefix',
            field=models.CharField(default='001', max_length=10),
        ),
    ]
