# Generated by Django 4.0.4 on 2023-01-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0031_remove_calllog_country_calllog_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
