# Generated by Django 4.0.4 on 2023-01-31 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0032_alter_calllog_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='86', max_length=10)),
                ('file', models.CharField(blank=True, default='', max_length=10)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
