# Generated by Django 4.0.4 on 2023-01-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0033_errorfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorfile',
            name='file',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
