# Generated by Django 4.0.4 on 2023-01-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0034_alter_errorfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorfile',
            name='file',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
