# Generated by Django 4.0.4 on 2023-02-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0036_errorfile_is_del'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gateway', max_length=50, verbose_name='Name')),
                ('ip', models.CharField(default='127.0.0.1', max_length=50, verbose_name='IP')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
