# Generated by Django 4.0.4 on 2023-02-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0037_outboundgateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Node', max_length=100, unique=True, verbose_name='Name')),
                ('ip', models.CharField(default='127.0.0.1', max_length=50, verbose_name='IP')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Blocked')),
            ],
        ),
    ]
