# Generated by Django 4.0.4 on 2023-02-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0038_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='name',
            field=models.CharField(default='Node', max_length=100, verbose_name='Name'),
        ),
    ]
