# Generated by Django 4.0.4 on 2023-03-04 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0039_alter_ip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundgateway',
            name='alert_enable',
            field=models.BooleanField(default=True, verbose_name='Enable Alert'),
        ),
        migrations.AddField(
            model_name='outboundgateway',
            name='cpu_cnt',
            field=models.IntegerField(default=0, verbose_name='CPU Count'),
        ),
        migrations.AddField(
            model_name='outboundgateway',
            name='cpu_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='CPU'),
        ),
        migrations.AddField(
            model_name='outboundgateway',
            name='cpu_used_percent',
            field=models.FloatField(default=0, verbose_name='CPU Used Percent'),
        ),
        migrations.AddField(
            model_name='outboundgateway',
            name='disk_total',
            field=models.BigIntegerField(default=0, verbose_name='Disk Total'),
        ),
        migrations.AddField(
            model_name='outboundgateway',
            name='disk_used',
            field=models.BigIntegerField(default=0, verbose_name='Disk Used'),
        ),
        migrations.AddField(
            model_name='outboundgateway',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Heartbeat'),
        ),
        migrations.AddField(
            model_name='outboundgateway',
            name='memory_total',
            field=models.BigIntegerField(default=0, verbose_name='Memory Total'),
        ),
        migrations.AddField(
            model_name='outboundgateway',
            name='memory_used',
            field=models.BigIntegerField(default=0, verbose_name='Memory Used'),
        ),
        migrations.AddField(
            model_name='outboundgateway',
            name='uptime',
            field=models.IntegerField(blank=True, default=0, verbose_name='Uptime'),
        ),
    ]
