# Generated by Django 4.0.4 on 2023-03-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0040_outboundgateway_alert_enable_outboundgateway_cpu_cnt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundgateway',
            name='internal_ip',
            field=models.CharField(default='127.0.0.1', max_length=50, verbose_name='Internal IP'),
        ),
    ]
