# Generated by Django 4.0.4 on 2023-03-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0042_outboundgateway_asterisk_current_calls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundgateway',
            name='version',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Version'),
        ),
    ]
