# Generated by Django 4.0.4 on 2023-03-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0043_outboundgateway_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cfg_silent',
            field=models.FloatField(default=0, verbose_name='Silent'),
        ),
    ]
