# Generated by Django 4.0.4 on 2023-03-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0044_customer_cfg_silent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cfg_peak_close_trunk',
            field=models.BooleanField(default=True, verbose_name='Peak Close Trunk'),
        ),
    ]
