# Generated by Django 4.0.4 on 2023-03-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voip', '0045_customer_cfg_peak_close_trunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cfg_carrier_ivr',
            field=models.BooleanField(default=True, verbose_name='Carrier IVR'),
        ),
    ]
